-- Admin Features Setup
-- Run this in Supabase SQL Editor

-- 1. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    target_user UUID REFERENCES auth.users(id),
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can read audit logs" ON public.audit_logs
    FOR SELECT USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

CREATE POLICY "Admins can insert audit logs" ON public.audit_logs
    FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

-- 2. Create Report Comments Table (for Admin/Student communication)
CREATE TABLE IF NOT EXISTS public.report_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT REFERENCES public.incident_reports(id),
    user_id UUID REFERENCES auth.users(id),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.report_comments ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can read comments on their own reports" ON public.report_comments
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.incident_reports 
            WHERE id = report_comments.report_id AND user_id = auth.uid()
        )
        OR
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

CREATE POLICY "Users can comment on their own reports" ON public.report_comments
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.incident_reports 
            WHERE id = report_comments.report_id AND user_id = auth.uid()
        )
    );

CREATE POLICY "Admins can comment on any report" ON public.report_comments
    FOR INSERT WITH CHECK (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );

-- 3. Fix Profiles RLS for Admin Elevation
-- Allow admins to update role
CREATE POLICY "Admins can update roles" ON public.profiles
    FOR UPDATE USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
    );
