-- Create Alerts Table
CREATE TABLE public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL, -- Storing Principal ID or Supabase User ID
    type TEXT NOT NULL, -- 'medical', 'fire', 'security', 'other'
    status TEXT NOT NULL DEFAULT 'active', -- 'active', 'resolved'
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    extra_data TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- Policy: Everyone can read active alerts (for the safety map)
CREATE POLICY "Public read access"
ON public.alerts FOR SELECT
USING (true);

-- Policy: Authenticated users can insert alerts
CREATE POLICY "User insert access"
ON public.alerts FOR INSERT
WITH CHECK (true); -- In prod, check auth.uid() = user_id

-- Policy: Responders/Admins can update status (Simplified for now)
CREATE POLICY "Public update access"
ON public.alerts FOR UPDATE
USING (true);
